#############################################################################
# Makefile for building: hw8
# Generated by qmake (2.01a) (Qt 4.8.6) on: Sun May 3 19:51:30 2015
# Project:  hw8.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile hw8.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = book.cpp \
		clothing.cpp \
		datastore.cpp \
		db_parser.cpp \
		info.cpp \
		login.cpp \
		main.cpp \
		main_window.cpp \
		movie.cpp \
		msort.cpp \
		popreview.cpp \
		popup.cpp \
		product.cpp \
		product_parser.cpp \
		recom.cpp \
		user.cpp \
		util.cpp moc_info.cpp \
		moc_login.cpp \
		moc_main_window.cpp \
		moc_popreview.cpp \
		moc_popup.cpp \
		moc_recom.cpp
OBJECTS       = book.o \
		clothing.o \
		datastore.o \
		db_parser.o \
		info.o \
		login.o \
		main.o \
		main_window.o \
		movie.o \
		msort.o \
		popreview.o \
		popup.o \
		product.o \
		product_parser.o \
		recom.o \
		user.o \
		util.o \
		moc_info.o \
		moc_login.o \
		moc_main_window.o \
		moc_popreview.o \
		moc_popup.o \
		moc_recom.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		hw8.pro
QMAKE_TARGET  = hw8
DESTDIR       = 
TARGET        = hw8

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: hw8.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile hw8.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile hw8.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/hw81.0.0 || $(MKDIR) .tmp/hw81.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hw81.0.0/ && $(COPY_FILE) --parents bst.h datastore.h db_parser.h heap.h info.h login.h main_window.h msort.h popreview.h popup.h product.h product_parser.h recom.h review.h splay.h user.h util.h .tmp/hw81.0.0/ && $(COPY_FILE) --parents book.cpp clothing.cpp datastore.cpp db_parser.cpp info.cpp login.cpp main.cpp main_window.cpp movie.cpp msort.cpp popreview.cpp popup.cpp product.cpp product_parser.cpp recom.cpp user.cpp util.cpp .tmp/hw81.0.0/ && (cd `dirname .tmp/hw81.0.0` && $(TAR) hw81.0.0.tar hw81.0.0 && $(COMPRESS) hw81.0.0.tar) && $(MOVE) `dirname .tmp/hw81.0.0`/hw81.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hw81.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_info.cpp moc_login.cpp moc_main_window.cpp moc_popreview.cpp moc_popup.cpp moc_recom.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_info.cpp moc_login.cpp moc_main_window.cpp moc_popreview.cpp moc_popup.cpp moc_recom.cpp
moc_info.cpp: main_window.h \
		popup.h \
		product.h \
		datastore.h \
		user.h \
		util.h \
		review.h \
		splay.h \
		bst.h \
		db_parser.h \
		product_parser.h \
		popreview.h \
		recom.h \
		info.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) info.h -o moc_info.cpp

moc_login.cpp: main_window.h \
		popup.h \
		product.h \
		datastore.h \
		user.h \
		util.h \
		review.h \
		splay.h \
		bst.h \
		db_parser.h \
		product_parser.h \
		popreview.h \
		recom.h \
		info.h \
		login.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) login.h -o moc_login.cpp

moc_main_window.cpp: popup.h \
		product.h \
		datastore.h \
		user.h \
		util.h \
		review.h \
		splay.h \
		bst.h \
		db_parser.h \
		product_parser.h \
		popreview.h \
		recom.h \
		main_window.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) main_window.h -o moc_main_window.cpp

moc_popreview.cpp: product.h \
		datastore.h \
		user.h \
		util.h \
		review.h \
		splay.h \
		bst.h \
		db_parser.h \
		product_parser.h \
		popreview.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) popreview.h -o moc_popreview.cpp

moc_popup.cpp: product.h \
		datastore.h \
		user.h \
		util.h \
		review.h \
		splay.h \
		bst.h \
		db_parser.h \
		product_parser.h \
		popup.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) popup.h -o moc_popup.cpp

moc_recom.cpp: datastore.h \
		product.h \
		user.h \
		util.h \
		review.h \
		splay.h \
		bst.h \
		recom.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) recom.h -o moc_recom.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

book.o: book.cpp product.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o book.o book.cpp

clothing.o: clothing.cpp product.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clothing.o clothing.cpp

datastore.o: datastore.cpp datastore.h \
		product.h \
		user.h \
		util.h \
		review.h \
		splay.h \
		bst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datastore.o datastore.cpp

db_parser.o: db_parser.cpp db_parser.h \
		datastore.h \
		product.h \
		user.h \
		util.h \
		review.h \
		splay.h \
		bst.h \
		product_parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o db_parser.o db_parser.cpp

info.o: info.cpp info.h \
		main_window.h \
		popup.h \
		product.h \
		datastore.h \
		user.h \
		util.h \
		review.h \
		splay.h \
		bst.h \
		db_parser.h \
		product_parser.h \
		popreview.h \
		recom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o info.o info.cpp

login.o: login.cpp login.h \
		main_window.h \
		popup.h \
		product.h \
		datastore.h \
		user.h \
		util.h \
		review.h \
		splay.h \
		bst.h \
		db_parser.h \
		product_parser.h \
		popreview.h \
		recom.h \
		info.h \
		heap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o login.cpp

main.o: main.cpp main_window.h \
		popup.h \
		product.h \
		datastore.h \
		user.h \
		util.h \
		review.h \
		splay.h \
		bst.h \
		db_parser.h \
		product_parser.h \
		popreview.h \
		recom.h \
		login.h \
		info.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

main_window.o: main_window.cpp main_window.h \
		popup.h \
		product.h \
		datastore.h \
		user.h \
		util.h \
		review.h \
		splay.h \
		bst.h \
		db_parser.h \
		product_parser.h \
		popreview.h \
		recom.h \
		msort.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_window.o main_window.cpp

movie.o: movie.cpp product.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o movie.o movie.cpp

msort.o: msort.cpp msort.h \
		product.h \
		review.h \
		datastore.h \
		user.h \
		util.h \
		splay.h \
		bst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o msort.o msort.cpp

popreview.o: popreview.cpp popreview.h \
		product.h \
		datastore.h \
		user.h \
		util.h \
		review.h \
		splay.h \
		bst.h \
		db_parser.h \
		product_parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o popreview.o popreview.cpp

popup.o: popup.cpp popup.h \
		product.h \
		datastore.h \
		user.h \
		util.h \
		review.h \
		splay.h \
		bst.h \
		db_parser.h \
		product_parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o popup.o popup.cpp

product.o: product.cpp product.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o product.o product.cpp

product_parser.o: product_parser.cpp product_parser.h \
		product.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o product_parser.o product_parser.cpp

recom.o: recom.cpp recom.h \
		datastore.h \
		product.h \
		user.h \
		util.h \
		review.h \
		splay.h \
		bst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o recom.o recom.cpp

user.o: user.cpp user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o user.cpp

util.o: util.cpp util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o util.cpp

moc_info.o: moc_info.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_info.o moc_info.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_main_window.o: moc_main_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main_window.o moc_main_window.cpp

moc_popreview.o: moc_popreview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_popreview.o moc_popreview.cpp

moc_popup.o: moc_popup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_popup.o moc_popup.cpp

moc_recom.o: moc_recom.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_recom.o moc_recom.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

